### ISSUE TITLE
Unable to start background process as root

### ISSUE THREAD

**Issue by yochananmarqos** [BitPonyLLC/huekeys#14] opened 2022-06-12 17:51 UTC
In the 0.5.0 changelog, you mention:

> no need to pass env to sudo ; use pkexec when not launched by terminal

However, that's not the case:

```
❯ huekeys menu
Error: unable to start background process as root
❯ pkexec huekeys menu
Error: unable to write to /tmp/huekeys-menu.pid: open /tmp/huekeys-menu.pid: permission denied
❯ sudo huekeys menu
Error: unable to write to /tmp/huekeys-menu.pid: open /tmp/huekeys-menu.pid: permission denied
```

**Comment by bradrf** [comment] 2022-06-12 21:35
@yochananmarqos thanks for letting me know this isn't working for you! Can you send me any logs you see from the background process? In other words is there anything you find from a command like this?
```shell
grep huekeys /var/log/syslog
```
I'm unable to reproduce what you're seeing.

Also, another thing to try to determine what's wrong is to run the same background process directlly, something like this:
```shell
sudo `which huekeys` --log-dst stdout --log-level trace run wait
```

**Comment by yochananmarqos** [comment] 2022-06-12 22:20
>```
> grep huekeys /var/log/syslog
>```

Arch based distros do not use `syslog`, so for me it would be `journalctl -b | grep huekeys`:

```
Jun 12 11:46:01 serval sudo[138141]: yochanan : TTY=pts/1 ; PWD=/mnt/storage/makepkg ; USER=root ; COMMAND=/usr/bin/sh -c export DESKTOP_PATTERN=eyJVc2VyIjoieW9jaGFuYW4iLCJSdW50aW1lRGlyIjoiL3J1bi91c2VyLzEwMDAifQ; exec /usr/bin/huekeys --config  run wait &
Jun 12 11:46:01 serval huekeys[138133]: ERR command failed error="unable to start background process as root"
Jun 12 11:48:19 serval org.gnome.gedit[4936]: KeyError: 'file:///var/lib/chrootbuild/build/huekeys/src/huekeys/.git'
Jun 12 11:48:19 serval org.gnome.gedit[4936]: KeyError: 'file:///var/lib/chrootbuild/build/huekeys/src/huekeys/.git'
Jun 12 11:49:22 serval pkexec[139417]: yochanan: Executing command [USER=root] [TTY=/dev/pts/1] [CWD=/mnt/storage/makepkg] [COMMAND=/usr/bin/huekeys menu]
Jun 12 11:49:22 serval huekeys[139417]: ERR command failed error="unable to write to /tmp/huekeys-menu.pid: open /tmp/huekeys-menu.pid: permission denied"
Jun 12 11:49:49 serval dbus-daemon[766]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.646' (uid=0 pid=139682 comm="sudo huekeys menu")
Jun 12 11:49:49 serval sudo[139682]: yochanan : TTY=pts/1 ; PWD=/mnt/storage/makepkg ; USER=root ; COMMAND=/usr/bin/huekeys menu
Jun 12 11:49:49 serval huekeys[139683]: ERR command failed error="unable to write to /tmp/huekeys-menu.pid: open /tmp/huekeys-menu.pid: permission denied"
Jun 12 11:52:22 serval sudo[140567]: yochanan : TTY=pts/1 ; PWD=/mnt/storage/makepkg ; USER=root ; COMMAND=/usr/bin/sh -c export DESKTOP_PATTERN=eyJVc2VyIjoieW9jaGFuYW4iLCJSdW50aW1lRGlyIjoiL3J1bi91c2VyLzEwMDAifQ; exec /usr/bin/huekeys --config  run wait &
Jun 12 11:52:22 serval huekeys[140556]: ERR command failed error="unable to start background process as root"
```

>```
>sudo `which huekeys` --log-dst stdout --log-level trace run wait
>```

```
16:18:58.780 DBG config file=
```

What config file? :thinking: 

EDIT: I think what is missing is a Polkit policy.

**Comment by bradrf** [comment] 2022-06-12 22:56
Aha! Yes, I see the bug and I can reproduce this, too! Thanks for the logs, they are very helpful (and good to know about Arch use of journalctl, thank you). I'll get a fix for this out right away.

As a workaround, I bet if you do the following things will start working for you:
```shell
sudo pkill huekeys
sudo rm -f /tmp/huekeys*
huekeys --dump-config > ~/.huekeys
huekeys menu
```

**Closed as completed** 2022-06-12 23:06 UTC
Labels: bug

**Comment by bradrf** [comment] 2022-06-12 23:15
Should be fixed in [v0.5.2](https://github.com/BitPonyLLC/huekeys/releases/tag/v0.5.2), but please re-open if you're still seeing any oddities. Thanks again!

**Comment by yochananmarqos** [comment] 2022-06-12 23:34
> As a workaround, I bet if you do the following...

That worked, indeed. I hadn't created a custom config as the defaults appeared to be fine. No issues updating to 0.5.2.

If you didn't already know, I've recently added this to the AUR: [`huekeys`](https://aur.archlinux.org/packages/huekeys)

**Comment by bradrf** [comment] 2022-06-13 13:48
That's awesome, @yochananmarqos, thanks for setting that up. I'd like to add that as another install option in the readme. However, when I tried to install, `pacman` doesn't seem to find it:
```shell
# pacman -Sy huekeys
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
error: target not found: huekeys
```
I don't use Arch, myself, so maybe I need to do something else to point to the right source?

**Comment by yochananmarqos** [comment] 2022-06-13 14:10
Pacman does not support the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository). 

You can do it manually:

```
sudo pacman -Syu --needed base-devel git
git clone https://aur.archlinux.org/huekeys.git
cd huekeys
makepkg -srcif
```

Or use an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers) like `yay`:

```
yay -S huekeys
```

**Comment by bradrf** [comment] 2022-06-13 23:55
Hmm, still not working for me, but this might be due to the severe minimalistic [docker container I'm using](https://hub.docker.com/_/archlinux/):
```shell
[foo@ceff34237886 huekeys]$ makepkg -srcif
==> Making package: huekeys 0.5.2-1 (Mon 13 Jun 2022 11:51:56 PM UTC)
==> Checking runtime dependencies...
==> Installing missing dependencies...

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for foo: 
error: target not found: system76-dkms
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> gtk3
  -> libayatana-appindicator
  -> system76-dkms
```

**Comment by yochananmarqos** [comment] 2022-06-13 23:56
> system76-dkms

Oops, forgot to mention that's an AUR package as well which needs to be installed first.
